---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
        - name: jenkins
          image: jenkins
          ports:
            - containerPort: 8080
              protocol: TCP