---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: NodePort
  selector:
    env: prod
  ports:
    - nodePort: 32500
      port: 8080
      targetPort: 8080
      protocol: TCP
